import { InjectRepository } from '@nestjs/typeorm';
import { Injectable } from '@nestjs/common';

import { Repository } from 'typeorm';

import { Employee, EmployeeArea, EmployeePosition } from './entities';
import { CreateEmployeeDto, UpdateEmployeeDto } from './dto';

@Injectable()
export class EmployeesService {
  constructor(
    @InjectRepository(Employee)
    private readonly employeeRepository: Repository<Employee>,
    @InjectRepository(EmployeeArea)
    private readonly employeeAreaRepository: Repository<EmployeeArea>,
    @InjectRepository(EmployeePosition)
    private readonly employeePositionRepository: Repository<EmployeePosition>,
  ) {}

  create(createEmployeeDto: CreateEmployeeDto) {
    return createEmployeeDto;
  }

  async seed() {
    const data = [
      {
        code: 10001,
        name: 'GAMEZ BORJA OTHONIEL',
        area: 'Logística',
        position: 'Operador de Montacargas',
      },
      {
        code: 10002,
        name: 'BAUTISTA RECENDIZ LILIA',
        area: 'Producción',
        position: 'Operador de Empaque  Encelofanadora',
      },
      {
        code: 10003,
        name: 'FERNANDEZ CANELA CLAUDIA',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10004,
        name: 'GARCIA ANGELES EDUARDO',
        area: 'Logística',
        position: 'Operador de Montacargas',
      },
      {
        code: 10005,
        name: 'GARCIA GUADALUPE MARIA DOLORES',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10007,
        name: 'LUVIANO GANDARILLA MA. GUADALUPE',
        area: 'Producción',
        position: 'Operador de Acabado',
      },
      {
        code: 10011,
        name: 'SANDOVAL GUADALUPE MARIA ANGELICA',
        area: 'Producción',
        position: 'Operador de Montacargas  Delegada',
      },
      {
        code: 10016,
        name: 'RUEDAS MONTERO ALICIA',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10025,
        name: 'PEREZ FRAGOSO ELIZABETH',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10027,
        name: 'HUERTA ZAMORA PEDRO',
        area: 'Logística',
        position: 'Operador de Montacargas',
      },
      {
        code: 10028,
        name: 'ALVAREZ MAESTRE MARIA ENRIQUETA',
        area: 'CALIDAD',
        position: 'Auxiliar Control de Calidad N1 Empaque',
      },
      {
        code: 10029,
        name: 'GALINDO ZAVALA OFELIA',
        area: 'CALIDAD',
        position: 'Auxiliar Control de Calidad N1 Empaque',
      },
      {
        code: 10033,
        name: 'CUEVAS SOTO VERONICA',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10055,
        name: 'ORTEGA MALDONADO IVONNE ROCIO',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10059,
        name: 'HERRERA LUGO LAURA ERICA',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10067,
        name: 'HERNANDEZ GARCIA DOLORES',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10088,
        name: 'MEDINA CARRANZA SANDRA',
        area: 'Documentación',
        position: 'Operario Patinador  Documentación',
      },
      {
        code: 10112,
        name: 'GUERRA HERNANDEZ ELIZABETH',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10121,
        name: 'NOLASCO FLORES MONICA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10144,
        name: 'TREJO MARTINEZ CLAUDIA',
        area: 'Ingeniería',
        position: 'Operador de Ingenieria',
      },
      {
        code: 10151,
        name: 'GONZALEZ ALDANA LEONOR',
        area: 'Administración',
        position: 'Operario de Aseo',
      },
      {
        code: 10157,
        name: 'BERNAL RAMIREZ NOE',
        area: 'SISTEMA DE GESTION INTEGRAL',
        position: 'Operario de Aseo',
      },
      {
        code: 10163,
        name: 'RODRIGUEZ LUNA JOSE MELESIO',
        area: 'Logística',
        position: 'Operario de Aseo',
      },
      {
        code: 10165,
        name: 'GUZMAN COTA GABRIEL',
        area: 'Producción',
        position: 'Operador de Mezclado',
      },
      {
        code: 10184,
        name: 'BENITEZ AVILEZ LETICIA',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10196,
        name: 'MEJIA REYNA YADIRA MONSERRAT',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10208,
        name: 'SANCHEZ TORRES DIEGO',
        area: 'Logística',
        position: 'Operador de Montacargas',
      },
      {
        code: 10217,
        name: 'CORTES PEREZ IDALIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10218,
        name: 'TOLEDO GUERRERO MARIA GUADALUPE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10222,
        name: 'URIBE HERNANDEZ MARIA ABRIL',
        area: 'Producción',
        position: 'Operario Patinador  Documentación',
      },
      {
        code: 10225,
        name: 'HERNANDEZ HERRERA ANAYELI',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10228,
        name: 'FERRER JIMENEZ ROSA MARIA',
        area: 'Producción',
        position: 'Operador de Empaque  Encelofanadora',
      },
      {
        code: 10233,
        name: 'NIETO MONTERO LYDIA GUADALUPE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10235,
        name: 'SANTIAGO TREJO LAURA',
        area: 'Producción',
        position: 'Operario de Aseo',
      },
      {
        code: 10237,
        name: 'GRIMALDO BENITEZ ANDREA',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10240,
        name: 'LOPEZ VANEGAS JANET',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10256,
        name: 'LORENZO AGUILAR TERESA YOSELIN',
        area: 'Producción',
        position: 'Operador de empaque Encelofanadora',
      },
      {
        code: 10266,
        name: 'LOPEZ SANDOVAL JOVANA',
        area: 'Documentación',
        position: 'Operario Patinador  Documentación',
      },
      {
        code: 10272,
        name: 'PAREDES CASTILLO VERONICA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10284,
        name: 'CHAVARRIA PACHECO MA. GEORGINA',
        area: 'Producción',
        position: 'Operario de Aseo',
      },
      {
        code: 10285,
        name: 'GONZALEZ GONZALEZ SANDRA',
        area: 'Producción',
        position: 'Analista de Información',
      },
      {
        code: 10298,
        name: 'SALAZAR GARCIA VICTOR MANUEL',
        area: 'Producción',
        position: 'Operador de Mezclado',
      },
      {
        code: 10304,
        name: 'VELEZ GARCIA GUADALUPE',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10305,
        name: 'GARCIA NAVA KAROL DENISSE',
        area: 'Producción',
        position: 'Operario Patinador  Documentación',
      },
      {
        code: 10316,
        name: 'MEDEL CONTRERAS GEORGINA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10318,
        name: 'ROSAS CHONA DIMAS',
        area: 'Producción',
        position: 'Operario de Aseo',
      },
      {
        code: 10319,
        name: 'LEDEZMA MARTINEZ NORMA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10339,
        name: 'NONIGO FILETE ROQUE',
        area: 'Producción',
        position: 'Operador de Mezclado',
      },
      {
        code: 10340,
        name: 'GONZALEZ ZARAZUA JUDITH',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10342,
        name: 'ISIDOR VAZQUEZ DIANA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10343,
        name: 'ROMERO RAMIREZ MARICELA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10345,
        name: 'BLAS SANCHEZ ZULEIMA YAREL',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10351,
        name: 'VILLEGAS VAZQUEZ CHRISTIAN',
        area: 'Producción',
        position: 'Operario Patinador  Documentación',
      },
      {
        code: 10363,
        name: 'GONZALEZ MARTINEZ SANDRA LUZ',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10364,
        name: 'HERNANDEZ HERNANDEZ BONIFACIO',
        area: 'Producción',
        position: 'Operador de Acabado',
      },
      {
        code: 10367,
        name: 'MARTINEZ JIMENEZ YENISET',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10369,
        name: 'MARTINEZ HERNANDEZ EDUARDO',
        area: 'Producción',
        position: 'Operador de Mezclado',
      },
      {
        code: 10385,
        name: 'CRUZ SANCHEZ MARGARITA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10389,
        name: 'COLIN ALMARAZ MARIA AZUCENA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10391,
        name: 'VAZQUEZ MENDEZ LINA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10396,
        name: 'CRUZ VAZQUEZ KARINA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10397,
        name: 'SALAS JIMENEZ CESAR',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10399,
        name: 'SERRANO SOTO JADRA MELISSA',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10412,
        name: 'CISNEROS BENITO REYNA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10415,
        name: 'ALVARADO HERNANDEZ MARICELA',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10426,
        name: 'BASTIDA PEREZ CARINA YESICA',
        area: 'Producción',
        position: 'Operador de Mezclado',
      },
      {
        code: 10431,
        name: 'MEZQUITIC VAZQUEZ DULCE MARIA GUADALUPE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10434,
        name: 'TINOCO AVILA OFELIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10437,
        name: 'MILLAN RIVERA MARISOL',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10446,
        name: 'ROSALES MENDOZA MARIA CRISTINA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10450,
        name: 'BARCENAS FORTIN JESSICA MIRIAM',
        area: 'Producción',
        position: 'Operador de empaque Liquidos',
      },
      {
        code: 10454,
        name: 'MONTOYA ALVAREZ JUANA ANTONIA',
        area: 'Producción',
        position: 'Operario de Aseo',
      },
      {
        code: 10457,
        name: 'DE ALBA PEREZ ALICIA JACQUELIN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10463,
        name: 'ORTIZ CORTES GENOVEVA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10472,
        name: 'GARAY CRUZ ROSA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10473,
        name: 'BAUTISTA MARTINEZ OBDULIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10474,
        name: 'BARONA JUAREZ OLGA LILIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10476,
        name: 'MORALES GUADALUPE MAIRA ELIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10477,
        name: 'FLORES SALAZAR ANA KAREN',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10478,
        name: 'GARCIA GALINDO ROCIO',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10479,
        name: 'VILLA BAUTISTA FRANCISCA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10489,
        name: 'VAQUERO SANTES ANGELINA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10490,
        name: 'MARTINEZ SANCHEZ JUDITH',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10491,
        name: 'LARA BARRERA TANIA ITZEL',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10496,
        name: 'MUÑOZ RAMOS SILVIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10499,
        name: 'BARRIOS GOMEZ YARELI SARAI',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10500,
        name: 'BADILLO CASTULO PATRICIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10508,
        name: 'VAZQUEZ RAMIREZ BERENICE',
        area: 'Producción',
        position: 'Operario Ayudante de Mezclado',
      },
      {
        code: 10510,
        name: 'BASURTO CAMPUZANO ANA LAURA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10522,
        name: 'PEREZ ANGELES ANAYELI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10526,
        name: 'LOYDA OLIVARES ROSA IDALIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10529,
        name: 'PEREZ JUAREZ J. JESUS',
        area: 'Producción',
        position: 'Operador de Acabado',
      },
      {
        code: 10531,
        name: 'RAMIREZ MALDONADO BRENDA GUADALUPE',
        area: 'Producción',
        position: 'Operario Documental',
      },
      {
        code: 10533,
        name: 'RAMIREZ ZAMORA MIREYA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10536,
        name: 'ALVAREZ ESQUIVEL ELSA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10545,
        name: 'ENCISO CRUZ DIANA SARAHI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10550,
        name: 'HERNANDEZ CORTES ARACELI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10564,
        name: 'LEON GONZALEZ TERESITA DE JESUS',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10590,
        name: 'RODRIGUEZ DOMINGUEZ BRENDA',
        area: 'CALIDAD',
        position: 'Auxiliar Control de Calidad N1 Empaque',
      },
      {
        code: 10594,
        name: 'CHAVARRIA COLIN JANET',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10600,
        name: 'DIAZ LOZANO DANIEL',
        area: 'Logística',
        position: 'Operador de Montacargas',
      },
      {
        code: 10603,
        name: 'AMARO AGUILAR MELANIE JAZMIN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10612,
        name: 'OCHOA SANCHEZ GEORGINA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10615,
        name: 'RODRIGUEZ CORONA ALONDRA ESTEFANIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10618,
        name: 'MENDEZ CIRIACO MARIA FERNANDA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10632,
        name: 'VELAZQUEZ MENDEZ RAQUEL',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10640,
        name: 'JUSTO SANCHEZ ANA LAURA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10645,
        name: 'CASTELLANOS NAJERA BIANCA',
        area: 'Logística',
        position: 'Operario de Aseo',
      },
      {
        code: 10648,
        name: 'ESCUDERO CORTES JESUS DAVID',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10649,
        name: 'REYES SALAS JOANA',
        area: 'Producción',
        position: 'Operador de Empaque',
      },
      {
        code: 10656,
        name: 'MONTOYA ORTIZ IVAN',
        area: 'Producción',
        position: 'Operario Ayudante de Mezclado',
      },
      {
        code: 10661,
        name: 'CRISTOBAL PEREZ MA. DE JESUS YULIANA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10676,
        name: 'MARTINEZ MARTINEZ MARIA DE LOS ANGELES',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10678,
        name: 'HERNANDEZ HERRERA LIZBETH',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10682,
        name: 'FLORES GARCIA CLARA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10687,
        name: 'CHAVARRIA ANGELES ARLETTE JAZMIN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10688,
        name: 'GUTIERREZ PEREA DAN YAEL',
        area: 'Producción',
        position: 'Operador de Mezclado',
      },
      {
        code: 10693,
        name: 'VELAZQUEZ SAUZA DIEGO',
        area: 'Producción',
        position: 'Operario Ayudante de Mezclado',
      },
      {
        code: 10705,
        name: 'CERVANTES GUTIERREZ RAQUEL',
        area: 'Producción',
        position: 'Operario de Aseo',
      },
      {
        code: 10706,
        name: 'LOPEZ RAMOS GLORIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10720,
        name: 'ROMERO SALAZAR YADIRA ASUNCION',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10723,
        name: 'GUTIERREZ MARQUEZ VANESSA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10736,
        name: 'TRUJILLO TEMAXTE MONICA',
        area: 'Producción',
        position: 'Operario de Calidad',
      },
      {
        code: 10737,
        name: 'BAILON CANDIA GRACIELA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10738,
        name: 'HERNANDEZ JUAREZ YESSICA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10742,
        name: 'JIMENEZ RODRIGUEZ KATHERINE DENISSE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10747,
        name: 'GOMEZ ARTEAGA ANTONIO',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10748,
        name: 'RODRIGUEZ CAUDILLO MAYTE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10750,
        name: 'SANCHEZ MARTINEZ MARIA ALICIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10752,
        name: 'CRUZ POLO JANETH PATRICIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10756,
        name: 'GUADALUPE VALENCIA MARIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10757,
        name: 'BARRERA MIL SANTANA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10758,
        name: 'HERNANDEZ PATIÑO VIANEY',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10759,
        name: 'VALDEZ PAEZ LILIANA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10760,
        name: 'CRUZ AGUILAR PATRICIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10761,
        name: 'SANCHEZ COLIN LAURA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10764,
        name: 'TREJO FLORES SANDRA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10767,
        name: 'FLORES GONZALEZ MARIA DEL CARMEN',
        area: 'Producción',
        position: 'Operario de Aseo',
      },
      {
        code: 10770,
        name: 'VALDEZ HERNANDEZ RICARDO',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10775,
        name: 'FRANCO AMADO BEATRIZ',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10777,
        name: 'REGINO ROSAS SELENE NOEMI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10779,
        name: 'MERCADO MARTINEZ MIGUEL ANGEL',
        area: 'Producción',
        position: 'Operario Ayudante de Mezclado',
      },
      {
        code: 10780,
        name: 'CASTAÑEDA JIMENEZ JESUS GUSTAVO',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10789,
        name: 'GOMEZ JUAREZ OSCAR',
        area: 'Producción',
        position: 'Operario Ayudante de Mezclado',
      },
      {
        code: 10791,
        name: 'CARBALLO ESTEBAN EDUARDO',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10792,
        name: 'MELENDEZ CRISTOBAL GONZALO',
        area: 'Logística',
        position: 'Operario Logistico',
      },
      {
        code: 10797,
        name: 'DOMINGUEZ VIDAL MARICELA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10799,
        name: 'DIAZ GARCIA VIRGINIA GABRIELA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10806,
        name: 'AGUILAR MENDOZA JUAN ANTONIO',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10807,
        name: 'DURAN VARGAS ROSALIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10808,
        name: 'MURILLO GUILLEN CLAUDIA ISELA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10809,
        name: 'TORRES LAUREANO YOLANDA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10813,
        name: 'BUSTOS MELO SELENE',
        area: 'CALIDAD',
        position: 'Auxiliar de Calidad N1',
      },
      {
        code: 10815,
        name: 'LOZANO RAMIREZ KAREN AZUCENA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10818,
        name: 'ARISTA CRUZ ANDREA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10819,
        name: 'FONES CARERA YARUMI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10820,
        name: 'GARFIAS TORRIJOS LILIANA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10821,
        name: 'MERCADO ESCALANTE DULCE SHECIT',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10822,
        name: 'ZAVALA MORENO MAURICIO FARID',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10823,
        name: 'AVENDAÑO LOPEZ MARIA GUADALUPE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10825,
        name: 'TOBANCHE DAVILA EDNA MARIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10827,
        name: 'AGUILAR CAMACHO YURITZY AMEYALIN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10831,
        name: 'VILLEGAS CHAVEZ GLORIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10832,
        name: 'VEGA GONZALEZ NANCY',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10833,
        name: 'CRUZ CORREA PERLA MARIANA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10837,
        name: 'LOPEZ NAVA SARAHI EVA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10840,
        name: 'GUTIERREZ RAMIREZ LLENI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10844,
        name: 'HUITRON GUERRERO LETICIA',
        area: 'Producción',
        position: 'Operario Documental',
      },
      {
        code: 10848,
        name: 'GONZALEZ GARCIA JAZMIN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10850,
        name: 'BAUTISTA GARCIA YESICA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10851,
        name: 'GONZALEZ TREJO PALOMA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10852,
        name: 'LUIS NONIGO MONICA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10860,
        name: 'RODRIGUEZ PACHECO CELINA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10861,
        name: 'BADILLO RUIZ CESAR JAIR',
        area: 'Producción',
        position: 'Operario Ayudante de Mezclado',
      },
      {
        code: 10863,
        name: 'PEREA MARCOS JOYCELYNN ANGIE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10866,
        name: 'VALERIO ARENAS AMAYRANI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10869,
        name: 'REYES HERNANDEZ EDITH',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10870,
        name: 'TORRES RODRIGUEZ DANIELA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10871,
        name: 'BACA SANCHEZ DANIEL EDUARDO',
        area: 'Logística',
        position: 'Operario Logistico',
      },
      {
        code: 10872,
        name: 'JACINTO ROJAS LUIS ENRIQUE',
        area: 'Logística',
        position: 'Operario Logistico',
      },
      {
        code: 10874,
        name: 'FLORES TOLEDO MARIA ELENA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10875,
        name: 'OROZCO MIGUEL OSVALDO ISRAEL',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10876,
        name: 'PINEDA ALVAREZ JOSE ENRIQUE',
        area: 'Logística',
        position: 'Operario Logistico',
      },
      {
        code: 10877,
        name: 'AGUADO DIAZ JOSE CARLOS',
        area: 'Logística',
        position: 'Operador de Montacargas',
      },
      {
        code: 10878,
        name: 'PEREZ BACA AMADO',
        area: 'Logística',
        position: 'Operador de Montacargas',
      },
      {
        code: 10879,
        name: 'CAMPOS GARCIA MAURICIO JASIEL',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10883,
        name: 'MORENO ARVIDE ERIKA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10884,
        name: 'TREJO CARRANZA LIRIDIANA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10885,
        name: 'MONTES MELENDEZ JAYAMELL',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10888,
        name: 'ROSAS JUAREZ ASAEL',
        area: 'Logística',
        position: 'Operador de Montacargas',
      },
      {
        code: 10890,
        name: 'SORIANO GARCIA VIRGINIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10892,
        name: 'SANCHEZ CRUZ ANGEL GUILLERMO',
        area: 'Logística',
        position: 'Operario Logistico',
      },
      {
        code: 10893,
        name: 'PAEZ CORDOVA ANGEL',
        area: 'Logística',
        position: 'Operario de Logística',
      },
      {
        code: 10894,
        name: 'ANGELES MURCIA ANGEL CESAR',
        area: 'Producción',
        position: 'Operario Ayudante de Mezclado',
      },
      {
        code: 10895,
        name: 'RIOS PRUNEDA FRANCISCO',
        area: 'Producción',
        position: 'Operario Ayudante de Mezclado',
      },
      {
        code: 10897,
        name: 'YAÑEZ ROJO GLORIA ALEJANDRA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10898,
        name: 'LARA AGUILAR ANA VIVIANA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10899,
        name: 'PEREZ SAN MARTIN MARIA EUGENIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10900,
        name: 'HERNANDEZ NOLASCO MARIA ISABEL',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10902,
        name: 'HERRERA HERNANDEZ ALEMA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10903,
        name: 'GALVEZ GARCIA NATALY AURORA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10904,
        name: 'GONZALEZ RAMIREZ ROSAURA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10905,
        name: 'FLORES ALDANA JAQUELIN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10906,
        name: 'RODRIGUEZ CAMPOS BRENDA MICHELLE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10907,
        name: 'GRIMALDO REYES ANDREA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10910,
        name: 'VILLALPANDO GOMEZ LETICIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10911,
        name: 'FRAGOSO ROJAS KENIA HAYDEE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10913,
        name: 'DIAZ SANCHEZ JORGE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10914,
        name: 'MARTINEZ SANCHEZ GRISELDA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10915,
        name: 'LOPEZ PEREZ CANDELARIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10916,
        name: 'PEREZ VALENCIA GABRIELA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10917,
        name: 'HERNANDEZ HERNANDEZ LUCIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10918,
        name: 'SANTIAGO OSORIO ANA MARIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10919,
        name: 'MARCELO HERNANDEZ ANA CARMEN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10920,
        name: 'MERCADO ESCAMILLA JOSE ALBERTO',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10923,
        name: 'RIVAS RICO DONOVAN FERNANDO',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10924,
        name: 'MONTOYA CHAVEZ LESLIE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10925,
        name: 'BOLAÑOS ENRIQUEZ JUAN JOSE',
        area: 'Logística',
        position: 'Operador de Montacargas',
      },
      {
        code: 10926,
        name: 'GOMEZ RODRIGUEZ VIRIDIANA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10927,
        name: 'TELLO MARCOS SHARENNY JISSEL',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10929,
        name: 'DURAN MARTINEZ ABRIL PAULINA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10933,
        name: 'LOPEZ SANCHEZ SONIA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10934,
        name: 'VIVAS CORONADO DIEGO ARMANDO',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10935,
        name: 'BERMUDEZ ROMERO VALERIA YOAXI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10936,
        name: 'SANCHEZ RAMIREZ MIGUEL ANGEL',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10937,
        name: 'GONZALEZ FLORES ANDIE MARGARITA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10938,
        name: 'NUÑEZ BARRAGAN YAZMIN GUADALUPE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10939,
        name: 'TEPOZ ARVISO MARIA ELENA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10940,
        name: 'MELGAREJO RODRIGUEZ JOCELYN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10941,
        name: 'JARDON GOMEZ SARA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10942,
        name: 'CARCAMO QUEZADA JOSELIN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10943,
        name: 'NORIEGA FIGUEROA INGRID SARAI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10944,
        name: 'FRAGOSO BELMONT PERLA ANDREA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10945,
        name: 'JIMENEZ CRUZ ITZEL AMAIRANY',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10946,
        name: 'TORRES SALAZAR WENDOLINE',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10947,
        name: 'MEDINA ROJAS TANIA MONSERRATH',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10948,
        name: 'MORENO DELGADO CINTIA JAZMIN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10949,
        name: 'SANTIAGO GUATEMALA SORI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10950,
        name: 'CARRANZA FLORES RAUL',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10951,
        name: 'CASTILLO CERVANTES LIZBETH',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10952,
        name: 'NAVA GARCIA JENNIFER',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10953,
        name: 'REYES SANDOVAL YESICA BEATRIZ',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10954,
        name: 'CRUZ GARCIA ANA KAREN',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10955,
        name: 'MARTINEZ FRAGOSO SARAI',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10956,
        name: 'MARQUEZ MONTOYA LESLIE MONTSERRAT',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10957,
        name: 'NOLASCO RAMIREZ JULIO CESAR',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10958,
        name: 'SANTANA MORALES DULCE GABRIELA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10959,
        name: 'ANTONIO REYES DULCE FERNANDA',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10960,
        name: 'RODRIGUEZ MENA NANCY',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10961,
        name: 'GIL RAMOS ALONDRA MICHEL',
        area: 'Producción',
        position: 'Operario General',
      },
      {
        code: 10962,
        name: 'CALVA VEGA DAVID ALEJANDRO',
        area: 'Logística',
        position: 'Operario Logistico',
      },
      {
        code: 20003,
        name: 'RODRIGUEZ RUIZ RENATO',
        area: 'Producción',
        position: 'Operador Líder de Maceraciones',
      },
      {
        code: 20005,
        name: 'GARCIA RAMIREZ VICTORIA',
        area: 'Innovación y Desarrollo',
        position: 'Coordinador de Innovación y desarrollo',
      },
      {
        code: 20007,
        name: 'RAMIREZ LOPEZ RAMON',
        area: 'CALIDAD',
        position: 'Director Técnico y Gestión Calidad',
      },
      {
        code: 20010,
        name: 'PEREZ LOPEZ VICTOR MANUEL',
        area: 'Ingeniería',
        position: 'Operador de Ingenieria',
      },
      {
        code: 20011,
        name: 'CASTILLO MORALES JANETH',
        area: 'Producción',
        position: 'Coordinador de Planeación',
      },
      {
        code: 20019,
        name: 'SANVICENTE MUCIÑO DAVID',
        area: 'Ingeniería',
        position: 'Coordinador Puesta a Punto',
      },
      {
        code: 20029,
        name: 'GUERRERO MELENDEZ KARINA',
        area: 'Innovación de empaques',
        position: 'Desarrollador de Empaques',
      },
      {
        code: 20031,
        name: 'GARCIA GARCIA JULIO CESAR',
        area: 'Ingeniería',
        position: 'Operador de Ingenieria',
      },
      {
        code: 20037,
        name: 'SALGADO GONZALEZ MARTHA GABRIELA',
        area: 'SISTEMA DE GESTION INTEGRAL',
        position: 'Jefe Sistema de Gestión',
      },
      {
        code: 20042,
        name: 'REYES TENORIO LUIS HECTOR',
        area: 'Tecnologia  y Soporte Tecnico',
        position: 'Analista de Soporte TIC',
      },
      {
        code: 20047,
        name: 'GONZALEZ LOPEZ ERICK',
        area: 'Ingeniería',
        position: 'Operador de Ingenieria',
      },
      {
        code: 20052,
        name: 'HERNANDEZ CRUZ ANA CRISTINA',
        area: 'COMERCIO EXTERIOR',
        position: 'Analista de Comercio Exterior',
      },
      {
        code: 20055,
        name: 'MEDINA NOGUEZ ALEJANDRO',
        area: 'CALIDAD',
        position: 'Coordinador de Control de Calidad',
      },
      {
        code: 20057,
        name: 'DOMINGUEZ CHAVEZ JUAN MANUEL',
        area: 'Ingeniería',
        position: 'Jefe de Proyectos',
      },
      {
        code: 20060,
        name: 'SPAGGIARI PINEDA DAVID',
        area: 'GERENCIA',
        position: 'Gerente General',
      },
      {
        code: 20069,
        name: 'GARRIDO RANGEL EDITH IRNZEN',
        area: 'CALIDAD',
        position: 'Analista Control de Calidad',
      },
      {
        code: 20071,
        name: 'MINILA PEREZ MARIA FERNANDA',
        area: 'CALIDAD',
        position: 'Analista Control de Calidad',
      },
      {
        code: 20072,
        name: 'ZUPPA FLAÑO ERNESTO',
        area: 'Producción',
        position: 'Coordinador de Producción',
      },
      {
        code: 20080,
        name: 'HERRERA NAVARRO GUSTAVO',
        area: 'Logística',
        position: 'Supervisor de Logística',
      },
      {
        code: 20081,
        name: 'GONZALEZ HERNANDEZ FROYLAN',
        area: 'Producción',
        position: 'Supervisor de Producción',
      },
      {
        code: 20082,
        name: 'TREJO MARTINEZ SONIA',
        area: 'Innovación y Desarrollo',
        position: 'Auxiliar de Innovación y Desarrollo',
      },
      {
        code: 20086,
        name: 'HERNANDEZ SAUCEDO JESSICA',
        area: 'Producción',
        position: 'Coordinador de Documentacion',
      },
      {
        code: 20090,
        name: 'GARCIA QUITERIO GABRIEL',
        area: 'Gestión Humana',
        position: 'Coordinador de Gestion Humana',
      },
      {
        code: 20094,
        name: 'SOLORIO CALVA ERICK',
        area: 'Ingeniería',
        position: 'Operador Administrativo de Ingeniería',
      },
      {
        code: 20096,
        name: 'LARIOS FRAGOSO KENIA DENISSE',
        area: 'SISTEMA DE GESTION INTEGRAL',
        position: 'Auxiliar de Sistema de Gestión',
      },
      {
        code: 20097,
        name: 'COLIN ANGUIANO MOISES',
        area: 'Ingeniería',
        position: 'Operador de Ingenieria',
      },
      {
        code: 20098,
        name: 'RANGEL NAVARRO ADRIAN',
        area: 'COMERCIO EXTERIOR',
        position: 'Analista de Comercio Exterior',
      },
      {
        code: 20099,
        name: 'VARGAS ANGEL LUCIANO',
        area: 'Producción',
        position: 'Coordinador de Producción',
      },
      {
        code: 20101,
        name: 'GARCIA BERNABE AMADO JOVANNI',
        area: 'Producción',
        position: 'Supervisor de Producción',
      },
      {
        code: 20103,
        name: 'MUÑOZ CASIQUE GISELA',
        area: 'FINANZAS',
        position: 'Jefe de Tesorería',
      },
      {
        code: 20107,
        name: 'RESENDIZ MORENO REYNA EDITH',
        area: 'Gestión Humana',
        position: 'Analista de Nomina N1',
      },
      {
        code: 20109,
        name: 'RILLO MORENO KEVIN IVANN',
        area: 'COMERCIAL',
        position: 'Coordinador Comercial',
      },
      {
        code: 20111,
        name: 'RAMIREZ PEREZ HIRAM JAVEL',
        area: 'Innovación de empaques',
        position: 'Desarrollador de Empaques',
      },
      {
        code: 20113,
        name: 'FANEITE URDANETA MISAEL JOSUE',
        area: 'Ingeniería',
        position: 'Coordinador de Mantenimiento y Confiabil',
      },
      {
        code: 20117,
        name: 'TRUJILLO GUERRERO MARIA SUSANA',
        area: 'Gestión Humana',
        position: 'Jefe de Gestión Humana',
      },
      {
        code: 20118,
        name: 'HERNANDEZ HERNANDEZ JOSE FERNANDO',
        area: 'Ingeniería',
        position: 'Operador de Ingenieria',
      },
      {
        code: 20120,
        name: 'RODRIGUEZ HERNANDEZ ALEXIS',
        area: 'Producción',
        position: 'Ingeniero de Procesos',
      },
      {
        code: 20124,
        name: 'ARRIETA MOSQUEDA OMAR ALFONSO',
        area: 'SST',
        position: 'Coordinador de Seguridad y Salud en el T',
      },
      {
        code: 20125,
        name: 'LOAIZA FRANCO DIEGO FERNANDO',
        area: 'Producción',
        position: 'Gerente de Produccion',
      },
      {
        code: 20127,
        name: 'PERALTA VERGARA LUZ STELLA',
        area: 'FINANZAS',
        position: 'Jefe de Contabilidad',
      },
      {
        code: 20133,
        name: 'ALEGRIA CARDENAS ALAN IVAN',
        area: 'Ingeniería',
        position: 'Operador de Ingenieria',
      },
      {
        code: 20134,
        name: 'SANCHEZ GONZALEZ EDUARDO',
        area: 'Ingeniería',
        position: 'Operador de Ingenieria',
      },
      {
        code: 20136,
        name: 'TREJO CABALLERO MARTHA BEATRIZ',
        area: 'FINANZAS',
        position: 'Jefe de Administración Tributaria',
      },
      {
        code: 20137,
        name: 'IMITOLA GONZALEZ ARNOLD ALBERTO',
        area: 'Ingeniería',
        position: 'Coordinador de Mantenimiento',
      },
      {
        code: 20138,
        name: 'SERRANO PALEMON DEISY NANCY',
        area: 'Gestión Humana',
        position: 'Analista de Nomina',
      },
      {
        code: 20139,
        name: 'DAVILA GOMEZ JOSHUA',
        area: 'FINANZAS',
        position: 'Analista de Impuestos',
      },
      {
        code: 20140,
        name: 'LOPEZ ZAMORANO ANA KAREN',
        area: 'FINANZAS',
        position: 'Auxiliar de Contabilidad',
      },
      {
        code: 20142,
        name: 'LOPEZ SILVA OSCAR URIEL',
        area: 'Logística',
        position: 'Auxiliar Administrativo Logística',
      },
      {
        code: 20143,
        name: 'ANGELES GUTIERREZ BRENDA',
        area: 'Gestión Humana',
        position: 'Auxiliar de Gestion Humana',
      },
      {
        code: 20144,
        name: 'SALINAS PEREZ MARIA DEL PILAR',
        area: 'Gestión Humana',
        position: 'Medico Laboral',
      },
      {
        code: 20145,
        name: 'JASSO HERNANDEZ YEDZI ALINE',
        area: 'Logística',
        position: 'Auxiliar Administrativo Logística',
      },
      {
        code: 20146,
        name: 'LEON ALCANTARA MIREYA RUBI',
        area: 'FINANZAS',
        position: 'Auxiliar de Impuestos',
      },
      {
        code: 20147,
        name: 'VALDEZ SANTIAGO RAUL',
        area: 'Logística',
        position: 'Auxiliar de Almacén de Refacciones',
      },
      {
        code: 20149,
        name: 'RUIZ RESENDIZ ERNESTO',
        area: 'Logística',
        position: 'Jefe de Logistica',
      },
      {
        code: 20150,
        name: 'SANCHEZ FELIX ERIKA',
        area: 'Ingeniería',
        position: 'Becario Ingenieria',
      },
      {
        code: 20151,
        name: 'LOMELI GUTIERREZ GUSTAVO OCTAVIO',
        area: 'Ingeniería',
        position: 'Operador de desarrollo tecnico',
      },
      {
        code: 20153,
        name: 'HERNANDEZ HERNANDEZ ALFREDO',
        area: 'CALIDAD',
        position: 'Analista de validaciones',
      },
      {
        code: 20154,
        name: 'RUIZ JARAMILLO MARTIN',
        area: 'Administración',
        position: 'Gerente Administrativo',
      },
      {
        code: 20155,
        name: 'GALINDO HERNANDEZ ALEXIA',
        area: 'Innovación de empaques',
        position: 'Auxiliar documental desarrollo de empaqu',
      },
      {
        code: 20156,
        name: 'HERNANDEZ RUIZ JUAN VICTOR',
        area: 'Innovación y Desarrollo',
        position: 'Analista de Innovación',
      },
      {
        code: 20157,
        name: 'HERNANDEZ SANJUANICO LAURA',
        area: 'Logística',
        position: 'Analista de Inventarios',
      },
      {
        code: 20159,
        name: 'OLGUIN CRUZ BRENDA',
        area: 'ADMINISTRACION Y FINANZAS',
        position: 'Auxiliar Administrativo',
      },
      {
        code: 20160,
        name: 'ARRELLIN PINEDA CARLOS ARTURO',
        area: 'Ingeniería',
        position: 'Coordinador de Automatizacion',
      },
      {
        code: 20161,
        name: 'MORALES AVILA MARIA FERNANDA',
        area: 'COMERCIAL',
        position: 'Ejecutiva de ventas',
      },
      {
        code: 20162,
        name: 'JIMENEZ JIMENEZ EDUARDO',
        area: 'Producción',
        position: 'Supervisor de Producción',
      },
      {
        code: 20165,
        name: 'GARCIA RAMIREZ STEVEN FERNANDO',
        area: 'INGENIERIA',
        position: 'Operador de Ingenieria',
      },
      {
        code: 20166,
        name: 'LOREDO RANGEL KEVIN ALEXIS',
        area: 'Ingeniería',
        position: 'Operador de Ingenieria',
      },
      {
        code: 20167,
        name: 'MONDRAGON AYALA CUAUHTEMOC ALEJANDRO',
        area: 'Ingeniería',
        position: 'Operador de Ingenieria',
      },
      {
        code: 20169,
        name: 'GARAY MENDOZA DIEGO',
        area: 'Logística',
        position: 'Auxiliar de Logistica',
      },
      {
        code: 20170,
        name: 'MARTINEZ HERNANDEZ ANDREA',
        area: 'CALIDAD',
        position: 'Auxiliar de Calidad',
      },
      {
        code: 20172,
        name: 'VILLEGAS ALVARADO LAURA ITZEL',
        area: 'Logística',
        position: 'Auxiliar Administrativo Logística',
      },
      {
        code: 20173,
        name: 'ALONSO SALVADOR ANA CECILIA',
        area: 'Innovación y Desarrollo',
        position: 'Analista de Innovación',
      },
      {
        code: 20174,
        name: 'CORONA HERRERA SHAMIR MANUEL',
        area: 'Innovación y Desarrollo',
        position: 'Analista de Innovación',
      },
      {
        code: 20175,
        name: 'RIVAS NICOLAS JORGE ALBERTO',
        area: 'Logística',
        position: 'Auxiliar Administrativo Logística',
      },
      {
        code: 20176,
        name: 'BOTELLO MONSIVAIS ELLIOT',
        area: 'CALIDAD',
        position: 'Analista de Calidad',
      },
      {
        code: 20177,
        name: 'MORAN GONZALEZ DIANA',
        area: 'CALIDAD',
        position: 'Analista de Calidad',
      },
      {
        code: 20178,
        name: 'MARQUEZ RIOS ABRAHAM',
        area: 'Logística',
        position: 'Supervisor de Logística',
      },
      {
        code: 20179,
        name: 'SANCHEZ NAJERA GIOVANNI',
        area: 'CALIDAD',
        position: 'Analista de Excelencia Corporativa',
      },
    ];

    for (const employee of data) {
      const area = employee.area;
      const position = employee.position;

      let currentArea = await this.employeeAreaRepository.findOne({
        where: { name: area },
      });
      let currentPosition = await this.employeePositionRepository.findOne({
        where: { name: position },
      });

      if (!currentArea) {
        currentArea = await this.employeeAreaRepository.save({ name: area });
      }

      if (!currentPosition) {
        currentPosition = await this.employeePositionRepository.save({
          name: position,
        });
      }

      await this.employeeRepository.save({
        code: employee.code,
        name: employee.name,
        area: currentArea,
        position: currentPosition,
      });
    }

    return { message: 'Seed completed successfully' };
  }

  findAll() {
    return this.employeeRepository.find({
      where: {
        isActive: true,
      },
      relations: ['area', 'position'],
      order: {
        name: 'ASC',
      },
    });
  }

  findOne(id: number) {
    return this.employeeRepository.findOne({
      where: {
        id,
        isActive: true,
      },
      relations: ['area', 'position'],
    });
  }

  update(id: number, updateEmployeeDto: UpdateEmployeeDto) {
    return { id, updateEmployeeDto };
  }

  remove(id: number) {
    return `This action removes a #${id} employee`;
  }
}
