export const EXTINGUISHER_INSPECTION_SEED_DATA = [
  {
    "location": "Caseta de vigilancia 1",
    "extinguisherNumber": "1",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Cuarto de maquinas",
    "extinguisherNumber": "2",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "cuarto de maq afuera",
    "extinguisherNumber": "3",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Tanques",
    "extinguisherNumber": "4",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Hidro",
    "extinguisherNumber": "5",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Recepción",
    "extinguisherNumber": "6",
    "typeOfExtinguisher": "CO2",
    "capacity": "2.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Sala alebrije",
    "extinguisherNumber": "7",
    "typeOfExtinguisher": "CO2",
    "capacity": "2.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Sala de juntas P.A",
    "extinguisherNumber": "8",
    "typeOfExtinguisher": "CO2",
    "capacity": "2.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Jefatura de compras",
    "extinguisherNumber": "9",
    "typeOfExtinguisher": "CO2",
    "capacity": "2.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Jefatura de gestión",
    "extinguisherNumber": "10",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Sala de capacitación",
    "extinguisherNumber": "11",
    "typeOfExtinguisher": "CO2",
    "capacity": "2.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "SITE",
    "extinguisherNumber": "12",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Acceso planta",
    "extinguisherNumber": "13",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Pasillo gris",
    "extinguisherNumber": "14",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Comedor",
    "extinguisherNumber": "15",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Comedor",
    "extinguisherNumber": "16",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Acceso comedor",
    "extinguisherNumber": "17",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Pasillo principal",
    "extinguisherNumber": "18",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Laboratorio innovación",
    "extinguisherNumber": "19",
    "typeOfExtinguisher": "PQS",
    "capacity": "4.5",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Lab fisico quimico",
    "extinguisherNumber": "20",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Pasillo principal",
    "extinguisherNumber": "21",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Almacen troqueles",
    "extinguisherNumber": "22",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Almacen repuestos",
    "extinguisherNumber": "23",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Tableros electricos",
    "extinguisherNumber": "24",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Pasillo principal",
    "extinguisherNumber": "25",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Pasillo principal",
    "extinguisherNumber": "26",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Sistema omosis",
    "extinguisherNumber": "27",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Pasillo principal",
    "extinguisherNumber": "28",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Making PB",
    "extinguisherNumber": "29",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Pasillo MP",
    "extinguisherNumber": "30",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Making 2 PB",
    "extinguisherNumber": "31",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Making 1 PB",
    "extinguisherNumber": "32",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Pasillo MP",
    "extinguisherNumber": "33",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Pasillo MP",
    "extinguisherNumber": "34",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Liquidos 1",
    "extinguisherNumber": "35",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "liquidos 1",
    "extinguisherNumber": "36",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "liquidos 2",
    "extinguisherNumber": "37",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "liquidos 2",
    "extinguisherNumber": "38",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "liquidos 3",
    "extinguisherNumber": "39",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "liquidos 3",
    "extinguisherNumber": "40",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "liquidos 4",
    "extinguisherNumber": "41",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "prepesas MK 4",
    "extinguisherNumber": "42",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Making 3 PA",
    "extinguisherNumber": "43",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Making 2 PA",
    "extinguisherNumber": "44",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "Making 1 PA",
    "extinguisherNumber": "45",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "caldera",
    "extinguisherNumber": "46",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "caldera",
    "extinguisherNumber": "47",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "empaque",
    "extinguisherNumber": "48",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Almacen retenciones",
    "extinguisherNumber": "49",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "oficina almacen",
    "extinguisherNumber": "50",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "almacen",
    "extinguisherNumber": "51",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "anden 3",
    "extinguisherNumber": "52",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "Cortina",
    "extinguisherNumber": "53",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "almacen",
    "extinguisherNumber": "54",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "almacen pasillo L-K",
    "extinguisherNumber": "55",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "pasillo almacen",
    "extinguisherNumber": "56",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "almacen temporal",
    "extinguisherNumber": "57",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "almacen temporal",
    "extinguisherNumber": "58",
    "typeOfExtinguisher": "PQS",
    "capacity": "10",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "almacen",
    "extinguisherNumber": "59",
    "typeOfExtinguisher": "PQS",
    "capacity": "10",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "pasillo virgen",
    "extinguisherNumber": "60",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "pasillo virgen",
    "extinguisherNumber": "61",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "subestacion",
    "extinguisherNumber": "62",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "subestacion",
    "extinguisherNumber": "63",
    "typeOfExtinguisher": "CO2",
    "capacity": "4.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "cuarto de montacargas",
    "extinguisherNumber": "64",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "caseta vigilancia 2",
    "extinguisherNumber": "65",
    "typeOfExtinguisher": "CO2",
    "capacity": "2.5",
    "pressureManometer": "NA",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-04-01",
    "maintenanceDate": "2024-04-01",
    "observations": ""
  },
  {
    "location": "caseta vigilancia 2",
    "extinguisherNumber": "66",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "montacargas crown1",
    "extinguisherNumber": "67",
    "typeOfExtinguisher": "PQS",
    "capacity": "1",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "montacargas crown 2",
    "extinguisherNumber": "68",
    "typeOfExtinguisher": "PQS",
    "capacity": "1",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "patineta",
    "extinguisherNumber": "69",
    "typeOfExtinguisher": "PQS",
    "capacity": "1",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "reserva",
    "extinguisherNumber": "70",
    "typeOfExtinguisher": "PQS",
    "capacity": "6",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  },
  {
    "location": "reserva",
    "extinguisherNumber": "71",
    "typeOfExtinguisher": "PQS",
    "capacity": "4.5",
    "pressureManometer": "C",
    "valve": "C",
    "hose": "C",
    "cylinder": "C",
    "barrette": "C",
    "seal": "C",
    "cornet": "C",
    "access": "C",
    "support": "C",
    "signaling": "C",
    "nextRechargeDate": "2024-08-01",
    "maintenanceDate": "2024-08-01",
    "observations": ""
  }
] as const;
