export const ZONES_SEED_DATA = [
  { area: 'Alfacer ', zone: 'Alfacer - Baños Mujeres' },
  { area: 'Alfacer ', zone: 'Alfacer - Recepción' },
  { area: 'Administración Fase 1', zone: 'Bodega de útiles de aseo' },
  { area: 'Casino Fase 4', zone: 'Casino Fase 4' },
  { area: 'Laboratorios de calidad', zone: 'Laboratorio de panel de olor' },
  { area: 'Mezclado', zone: 'Mezclado - Área de lavado Fase 1' },
  { area: 'Mezclado', zone: 'Mezclado - Área de lavado Fase 4' },
  { area: 'Mezclado', zone: 'Mezclado - Zona de pesaje Línea 5' },
  {
    area: 'Líquidos',
    zone: 'Planta de Líquidos - Preparación Línea 2',
  },
  { area: 'Solidos', zone: 'Producción acabado Línea 10' },
  { area: 'Solidos', zone: 'Producción acabado Línea 11' },
  { area: 'Solidos', zone: 'Producción acabado Línea 12' },
  { area: 'Solidos', zone: 'Producción acabado Línea 13' },
  { area: 'Solidos', zone: 'Acabado fase 4' },
  { area: 'Alfacer ', zone: 'Alfacer - Área de alistamiento' },
  { area: 'Alfacer ', zone: 'Alfacer - Área perimetral' },
  { area: 'Alfacer ', zone: 'Alfacer - Baños Hombres' },
  { area: 'Alfacer ', zone: 'Alfacer - Bodega de almacenamiento' },
  { area: 'Alfacer ', zone: 'Alfacer - Cafetería' },
  { area: 'Alfacer ', zone: 'Alfacer - Cuarto de aseo' },
  { area: 'Alfacer ', zone: 'Alfacer - Cuarto de conductores' },
  { area: 'Alfacer ', zone: 'Alfacer - Datacenter' },
  { area: 'Alfacer ', zone: 'Alfacer - Muelles exportación' },
  { area: 'Alfacer ', zone: 'Alfacer - Muelles nacionales' },
  { area: 'Alfacer ', zone: 'Alfacer - Oficinas' },
  { area: 'Alfacer ', zone: 'Alfacer - Vestier Hombres' },
  { area: 'Alfacer ', zone: 'Alfacer - Vestier Mujeres' },
  { area: 'Almacen', zone: 'Almacén de repuestos' },
  { area: 'Bodegas logistica', zone: 'Almacenamiento de molido' },
  { area: 'Solidos', zone: 'Area de devoluciones fase 4' },
  { area: 'Solidos', zone: 'Área de molino' },
  { area: 'Perimetros', zone: 'Área perimetral Hada international' },
  { area: 'Administración Fase 1', zone: 'Auditorio' },
  { area: 'Bodegas logistica', zone: 'Axia' },
  { area: 'Baños Fase 1', zone: 'Baño de hombres - Fase 1 Segundo piso' },
  {
    area: 'Baños Fase 1',
    zone: 'Baño de mujeres - Fase 1 Segundo piso',
  },
  {
    area: 'Bodegas logistica',
    zone: 'Bodega almacenamiento - Cabina de muestreo',
  },
  {
    area: 'Bodegas logistica',
    zone: 'Bodega almacenamiento - Cuarto de baterías Fase 2',
  },
  {
    area: 'Bodegas logistica',
    zone: 'Bodega almacenamiento - Cuarto de baterías Fase 4',
  },
  { area: 'Bodegas logistica', zone: 'Bodega almacenamiento Fase 1' },
  { area: 'Bodegas logistica', zone: 'Bodega almacenamiento Fase 4' },
  {
    area: 'Bodegas logistica',
    zone: 'Bodega de almacenamiento - Oficinas',
  },
  { area: 'Bodegas logistica', zone: 'Bodega de almacenamiento Fase 2' },
  {
    area: 'Bodegas logistica',
    zone: 'Bodega de elementos de protección personal',
  },
  { area: 'Bodegas logistica', zone: 'Bodega de Jabón Base' },
  { area: 'Bodegas logistica', zone: 'Bodega Mariana' },
  { area: 'Casino fase 1', zone: 'Casino fase 1' },
  { area: 'Centro de acopio', zone: 'Centro de acopio' },
  { area: 'Coldprocess', zone: 'Cold Process - Área de cortado' },
  { area: 'Coldprocess', zone: 'Cold Process - Área de curado' },
  {
    area: 'Coldprocess',
    zone: 'Cold Process - Área de dosificación de materia prima',
  },
  { area: 'Coldprocess', zone: 'Cold Process - Área de lavado' },
  { area: 'Coldprocess', zone: 'Cold Process - Área de secado' },
  { area: 'Coldprocess', zone: 'Cold Process - Área perimetral' },
  { area: 'Coldprocess', zone: 'Cold Process - Baño Hombres' },
  { area: 'Coldprocess', zone: 'Cold Process - Baño Mujeres' },
  { area: 'Coldprocess', zone: 'Cold Process - Bodega' },
  { area: 'Coldprocess', zone: 'Cold Process - Cabina de pesaje' },
  { area: 'Coldprocess', zone: 'Cold Process - Casino' },
  {
    area: 'Coldprocess',
    zone: 'Cold Process - Cuarto de almacenamiento de aceites',
  },
  { area: 'Coldprocess', zone: 'Cold Process - Esclusa de ingreso' },
  { area: 'Coldprocess', zone: 'Cold Process - Esclusa de personal' },
  { area: 'Coldprocess', zone: 'Cold Process - Mezclado' },
  { area: 'Coldprocess', zone: 'Cold Process - Oficina' },
  { area: 'Coldprocess', zone: 'Cold Process - Recepción' },
  { area: 'Coldprocess', zone: 'Cold Process - Vestier Hombres' },
  { area: 'Coldprocess', zone: 'Cold Process - Vestier Mujeres' },
  { area: 'Coldprocess', zone: 'Cold Process - Zona de empaque' },
  { area: 'Enfermeria', zone: 'Consultorio SST' },
  { area: 'Enfermeria', zone: 'Consultorio SST - Baño' },
  { area: 'Administración Fase 1', zone: 'Control de acceso Fase 1' },
  { area: 'Administración Fase 4', zone: 'Control de acceso Fase 4' },
  { area: 'Administración Fase 1', zone: 'Cuarto de conductores' },
  { area: 'Laboratorios de calidad', zone: 'Cuarto de contra muestra' },
  { area: 'Solidos', zone: 'Cuarto de lavado Fase 2' },
  { area: 'Talleres de mantenimiento', zone: 'Cuarto de lubricantes' },
  { area: 'Talleres de puesta a punto', zone: 'Cuarto de troqueles' },
  { area: 'Servicios Industriales', zone: 'Cuarto de valvulas de agua' },
  { area: 'Talleres de mantenimiento', zone: 'Cuarto técnico' },
  {
    area: 'Cuarto de residuos peligrosos',
    zone: 'Cuartos de residuos peligrosos',
  },
  { area: 'Solidos', zone: 'Datacenter fase 2' },
  { area: 'Patio de tanques', zone: 'Dique de patio tanque' },
  { area: 'Ecofire', zone: 'Ecofire - Área de empaque' },
  { area: 'Ecofire', zone: 'Ecofire - Área de prepesaje' },
  { area: 'Ecofire', zone: 'Ecofire - Cuarto de aires' },
  { area: 'Ecofire', zone: 'Ecofire - Cuarto de aseo' },
  { area: 'Ecofire', zone: 'Ecofire - Esclusa de ingreso' },
  { area: 'Ecofire', zone: 'Ecofire - Esclusa de materiales' },
  { area: 'Ecofire', zone: 'Ecofire - Iniciadores' },
  { area: 'Ecofire', zone: 'Ecofire - Preparación y prepesaje' },
  { area: 'Ecofire', zone: 'Ecofire - Velas' },
  { area: 'Ecofire', zone: 'Ecofire - Velas artesanales' },
  { area: 'Ecofire', zone: 'Ecofire Iniciadores - Esclusa de materiales' },
  { area: 'Ecofire', zone: 'Ecofire Iniciadores - Esclusa de personal' },
  { area: 'Enfermeria', zone: 'Enfermería ' },
  { area: 'Administración Fase 1', zone: 'Entrada fase 1' },
  {
    area: 'Laboratorios de calidad',
    zone: 'Laboratorio de análisis instrumental',
  },
  { area: 'Innovación', zone: 'Laboratorio de innovación' },
  {
    area: 'Laboratorios de calidad',
    zone: 'Laboratorio de material de empaque',
  },
  { area: 'Laboratorio de metrología', zone: 'Laboratorio de Metrología' },
  {
    area: 'Laboratorio de microbiología',
    zone: 'Laboratorio de microbiología',
  },
  { area: 'Laboratorios de calidad', zone: 'Laboratorio de saponificación' },
  { area: 'Laboratorios de calidad', zone: 'Laboratorio físico-químico' },
  { area: 'Ecofire', zone: 'Maceraciones' },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento de materias primas Línea 6',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento de materias primas productos especiales',
  },
  { area: 'Mezclado', zone: 'Mezclado - Almacenamiento materia prima Línea 1' },
  { area: 'Mezclado', zone: 'Mezclado - Almacenamiento materia prima Línea 2' },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento materia prima prepesada Línea 3',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento materias primas Línea 11',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento materias primas Línea 12',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento materias primas Línea 8',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento materias primas Línea 9',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento materias primas prepesadas Línea 10',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento materias primas prepesadas Línea 12',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento materias primas prepesadas Línea 6',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento materias primas prepesadas Línea 7',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Almacenamiento materias primas prepesadas Línea 8',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área almacenamiento materia prima Línea 3',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área almacenamiento materia prima Línea 5',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área almacenamiento materia prima prepesada Línea 4',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área almacenamiento materia prima prepesada Línea 5',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área de almacenamiento materia prima Línea 4',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área de almacenamiento materias primas Línea 13',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área de almacenamiento materias primas Línea 14',
  },
  { area: 'Mezclado', zone: 'Mezclado - Área de documentación' },
  { area: 'Mezclado', zone: 'Mezclado - Área de premezclas Fase 1' },
  { area: 'Mezclado', zone: 'Mezclado - Área de premezclas Fase 2' },
  { area: 'Mezclado', zone: 'Mezclado - Área de prepesaje Línea 10' },
  { area: 'Mezclado', zone: 'Mezclado - Área de prepesaje Línea 8 y 9' },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área de prepesaje materia prima Línea 11 y 12',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área de prepesaje materia prima Línea 13',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área de prepesaje materia prima Línea 14',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área prepesaje materia prima Línea 1-2',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Área prepesaje materia prima Línea 3 y 4',
  },
  { area: 'Mezclado', zone: 'Mezclado - Cuarto de lavado Fase 2' },
  { area: 'Mezclado', zone: 'Mezclado - Cuarto de lavado Fase 4' },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Dispensación de materias primas líquidas Línea 11',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Dispensación de materias primas líquidas Línea 12',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Dispensación de materias primas liquidas Línea 13',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Dispensación de materias primas liquidas Línea 14',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Dispensación de materias primas líquidas Línea 4',
  },
  {
    area: 'Mezclado',
    zone: 'Mezclado - Dispensación de materias primas líquidas Línea 9',
  },
  { area: 'Mezclado', zone: 'Mezclado - Esclusa de personal Fase 1' },
  { area: 'Mezclado', zone: 'Mezclado - Esclusa de personal Fase 2' },
  { area: 'Mezclado', zone: 'Mezclado - Esclusa de personal Fase 4' },
  { area: 'Mezclado', zone: 'Mezclado - Zona de pesaje Línea 7' },
  { area: 'Mezclado', zone: 'Mezclado Fase 1' },
  { area: 'Mezclado', zone: 'Mezclado Fase 2' },
  { area: 'Mezclado', zone: 'Mezclado Fase 4' },
  { area: 'Talleres de mantenimiento', zone: 'Oficina taller de ingeniería' },
  { area: 'Solidos', zone: 'Oficinas 1er piso Fase 1' },
  { area: 'Solidos', zone: 'Oficinas 1er piso Fase 2' },
  { area: 'Solidos', zone: 'Oficinas 1er piso Fase 4' },
  {
    area: 'Administración Fase 1',
    zone: 'Oficinas administrativas 1er piso Fase 1',
  },
  {
    area: 'Administración Fase 1',
    zone: 'Oficinas administrativas 2do piso Fase 1',
  },
  {
    area: 'Administración Fase 4',
    zone: 'Oficinas administrativas 2do piso Fase 4',
  },
  {
    area: 'Administración Fase 1',
    zone: 'Oficinas administrativas 3er piso Fase 1',
  },
  {
    area: 'Administración Fase 4',
    zone: 'Oficinas administrativas 3er piso Fase 4',
  },
  { area: 'Patio de tanques', zone: 'Patio de tanques' },
  { area: 'Líquidos', zone: 'Planta de líquidos - Cuarto de soplado' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Envasado Línea 1' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Envasado Línea 2' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Envasado Línea 3' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Envasado Línea 4' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Esclusa material 1er piso' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Esclusa material 2do piso' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Esclusa material 3er piso' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Esclusa personal' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Preparación Línea 1' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Preparación Línea 1' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Preparación Línea 2' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Preparación Línea 3' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Preparación Línea 3' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Preparación Línea 4' },
  { area: 'Líquidos', zone: 'Planta de Líquidos - Preparación Línea 4' },
  { area: 'Líquidos', zone: 'Planta tratamiento de agua' },
  { area: 'Solidos', zone: 'Producción acabado Línea 1' },
  { area: 'Solidos', zone: 'Producción acabado Línea 14' },
  { area: 'Solidos', zone: 'Producción acabado Línea 2' },
  { area: 'Solidos', zone: 'Producción acabado Línea 3' },
  { area: 'Solidos', zone: 'Producción acabado Línea 4' },
  { area: 'Solidos', zone: 'Producción acabado Línea 5' },
  { area: 'Solidos', zone: 'Producción acabado Línea 6' },
  { area: 'Solidos', zone: 'Producción acabado Línea 7' },
  { area: 'Solidos', zone: 'Producción acabado Línea 8' },
  { area: 'Solidos', zone: 'Producción acabado Línea 9' },
  { area: 'PTAR', zone: 'PTAR' },
  { area: 'PTAR', zone: 'PTAR - Laboratorio' },
  { area: 'Administración Fase 1', zone: 'Recepción Fase 1' },
  { area: 'Administración Fase 4', zone: 'Recepción Fase 4' },
  { area: 'Administración Fase 4', zone: 'Sala de capacitaciones Fase 4' },
  { area: 'Saponificación y secado', zone: 'Saponificación' },
  { area: 'Saponificación y secado', zone: 'Secado' },
  { area: 'Saponificación y secado', zone: 'Secado - Oficina' },
  { area: 'Servicios Industriales', zone: 'Servicios a la producción' },
  { area: 'Servicios Industriales', zone: 'Subestación eléctrica' },
  { area: 'Servicios Industriales', zone: 'Subestación eléctrica - Piso 2' },
  { area: 'Talleres de mantenimiento', zone: 'Taller de automatización' },
  { area: 'Talleres de mantenimiento', zone: 'Taller de bombas' },
  { area: 'Talleres de mantenimiento', zone: 'Taller de ingeniería eléctrica' },
  { area: 'Talleres de mantenimiento', zone: 'Taller de soldadura' },
  { area: 'Talleres de mantenimiento', zone: 'Taller mecánico' },
  { area: 'Servicios Industriales', zone: 'Torre de enfriamiento' },
  { area: 'Vestieres', zone: 'Vestidor - Baño contratista Fase 4' },
  { area: 'Vestieres', zone: 'Vestidor - Baño Hombres Fase 1' },
  { area: 'Vestieres', zone: 'Vestidor - Baño Hombres Fase 4' },
  { area: 'Vestieres', zone: 'Vestidor - Baño Mujeres Fase 1' },
  { area: 'Vestieres', zone: 'Vestidor - Baño Mujeres Fase 4' },
];
